<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29528" started-at="2021-12-27T20:10:20Z" finished-at="2021-12-27T20:10:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29528" started-at="2021-12-27T20:10:20Z" finished-at="2021-12-27T20:10:49Z">
      <class name="com.org.Testcases.Login_Page_Test">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.org.Testcases.Login_Page_Test@3ffcd140]" name="SetUp" is-config="true" duration-ms="15235" started-at="2021-12-28T01:40:20Z" finished-at="2021-12-28T01:40:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="Verify_Title()[pri:1, instance:com.org.Testcases.Login_Page_Test@3ffcd140]" name="Verify_Title" duration-ms="127" started-at="2021-12-28T01:40:35Z" finished-at="2021-12-28T01:40:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Title -->
        <test-method status="FAIL" signature="Verify_Login()[pri:2, instance:com.org.Testcases.Login_Page_Test@3ffcd140]" name="Verify_Login" duration-ms="9528" started-at="2021-12-28T01:40:35Z" finished-at="2021-12-28T01:40:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.org.Testcases.Login_Page_Test.Verify_Login(Login_Page_Test.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Login -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.org.Testcases.Login_Page_Test@3ffcd140]" name="TearDown" is-config="true" duration-ms="3927" started-at="2021-12-28T01:40:45Z" finished-at="2021-12-28T01:40:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.org.Testcases.Login_Page_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
